PRODUCT_SOONG_CONFIG_NAMESPACES += AVIUM
ifeq ($(AVIUM_FORCE_SET_FAKE_PROP),true)
PRODUCT_SOONG_CONFIG_AVIUM += AVIUM_FORCE_SET_FAKE_PROP:true
else
PRODUCT_SOONG_CONFIG_AVIUM += AVIUM_FORCE_SET_FAKE_PROP:false
endif